name: Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Prettier
        run: npm install --global prettier
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check src